### ISSUE TITLE
Discussion of default values

### ISSUE THREAD

**Issue by VisualSJ** [electron-utils/electron-profile#3]
I submitted a pr: 
https://github.com/electron-utils/electron-profile/pull/2

This pr has done a couple of things:

1. Increase profile inheritance
2. The data acquisition mode is changed to get/set

But one thing is not clear - Implementation of default values.

For example, local and global. When you can't find the local data, look for global data.
Is the default value found after you can't find local and gobal?

The previous implementation was to replace the existing data with the default values when the data was not found.

I don't know which would be better.

**Comment by VisualSJ** [comment]
关于 schema 与 default：

参考 vscode 内的实现，其实是自己实现了一套简化版的 schema，只有一个层级，type default description

schema 配置：
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/commonEditorConfig.ts#L170

实际最终注册代码：
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/configuration/common/configurationRegistry.ts#L168

然后有一个 jsonScanner 扫描 json 数据：
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/json.ts#L40
（这个还没弄清楚是怎么调用到的，但是应该是通过这个扫描的）

我的想法是弄个简单的 json scanner，然后定义如下 json 文件

```json
{
    "type": "object",
    "properties": {
        "foo": {
            "type": "object",
            "properties": {
                "bar": {
                    "type": "string",
                    "default": "test"
                }
            }
        }
    }
}
```

@jwu

**Comment by VisualSJ** [comment]
找遍了 creator，好像单层级不需要嵌套可以满足现有的所有需求。
现在按照单层的先做一个版本？
@jwu

**Comment by jwu** [comment]
恩，我觉得挺合理的，单层的 profile schema。其实嵌套需求就是字段中的 object type 而已
